package com.injian.dao;

import com.injian.dataobject.CategoryDO;

import java.util.List;

public interface CategoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    int insert(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    int insertSelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    CategoryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    int updateByPrimaryKeySelective(CategoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_category
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    int updateByPrimaryKey(CategoryDO record);
    List<CategoryDO> getCategoryList();
}