package com.injian.dao;

import com.injian.dataobject.OrderAddressStatusDO;

public interface OrderAddressStatusDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_status
     *
     * @mbg.generated Wed May 08 20:50:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_status
     *
     * @mbg.generated Wed May 08 20:50:14 CST 2019
     */
    int insert(OrderAddressStatusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_status
     *
     * @mbg.generated Wed May 08 20:50:14 CST 2019
     */
    int insertSelective(OrderAddressStatusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_status
     *
     * @mbg.generated Wed May 08 20:50:14 CST 2019
     */
    OrderAddressStatusDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_status
     *
     * @mbg.generated Wed May 08 20:50:14 CST 2019
     */
    int updateByPrimaryKeySelective(OrderAddressStatusDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_address_status
     *
     * @mbg.generated Wed May 08 20:50:14 CST 2019
     */
    int updateByPrimaryKey(OrderAddressStatusDO record);
    int deleteByOrderId(String orderId);
    OrderAddressStatusDO selectByOrderId(String orderId);
}