package com.injian.dao;

import com.injian.dataobject.UserAddressDO;

import java.util.List;

public interface UserAddressDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon May 06 15:24:47 CST 2019
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon May 06 15:24:47 CST 2019
     */
    int insert(UserAddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon May 06 15:24:47 CST 2019
     */
    int insertSelective(UserAddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon May 06 15:24:47 CST 2019
     */
    UserAddressDO selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon May 06 15:24:47 CST 2019
     */
    int updateByPrimaryKeySelective(UserAddressDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Mon May 06 15:24:47 CST 2019
     */
    int updateByPrimaryKey(UserAddressDO record);
    List<UserAddressDO> selectByUserId(Integer userId);
}