package com.injian.dataobject;

public class CategoryDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_category.id
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_category.name
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_category.parent_id
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_category.id
     *
     * @return the value of item_category.id
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_category.id
     *
     * @param id the value for item_category.id
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_category.name
     *
     * @return the value of item_category.name
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_category.name
     *
     * @param name the value for item_category.name
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_category.parent_id
     *
     * @return the value of item_category.parent_id
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_category.parent_id
     *
     * @param parentId the value for item_category.parent_id
     *
     * @mbg.generated Sun May 12 13:02:44 CST 2019
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}